version: "3"
services:
  frontend-app:
    build: ./frontend
    image: frontend:preview
    stdin_open: true
    ports:
      - "12000:8080"
    networks:
      - faq-app
    volumes:
      - .:/var/www/frontend
      - /var/www/frontend/node_modules
    environment:
      - npm_config_unsafe_perm=true
  api-server:
    build: ./backend
    image: backend:preview
    ports:
      - "3000:3000"
    networks:
      - faq-app
networks:
  faq-app:
    driver: bridge
